<?php

return [
    'mbbank' => 'MB Bank - Ngân hàng Quân đội',
    'vietcombank' => 'Vietcombank - Ngân hàng TMCP Ngoại thương Việt Nam',
    'vietinbank' => 'VietinBank - Ngân hàng TMCP Công thương Việt Nam',
    'bidv' => 'BIDV - Ngân hàng TMCP Đầu tư và Phát triển Việt Nam',
    'agribank' => 'Agribank - Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam',
    'acb' => 'ACB - Ngân hàng TMCP Á Châu',
    'techcombank' => 'Techcombank - Ngân hàng TMCP Kỹ thương Việt Nam',
    'sacombank' => 'Sacombank - Ngân hàng TMCP Sài Gòn Thương Tín',
    'vpbank' => 'VPBank - Ngân hàng TMCP Việt Nam Thịnh Vượng',
    'tpbank' => 'TPBank - Ngân hàng TMCP Tiên Phong',
    'shb' => 'SHB - Ngân hàng TMCP Sài Gòn – Hà Nội',
    'hdbank' => 'HDBank - Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh',
    'ocb' => 'OCB - Ngân hàng TMCP Phương Đông',
    'msb' => 'MSB - Ngân hàng TMCP Hàng Hải Việt Nam',
    'seabank' => 'SeABank - Ngân hàng TMCP Đông Nam Á',
    'vib' => 'VIB - Ngân hàng TMCP Quốc tế Việt Nam',
    'eximbank' => 'Eximbank - Ngân hàng TMCP Xuất Nhập khẩu Việt Nam',
    'lpbank' => 'LPBank - Ngân hàng TMCP Bưu điện Liên Việt',
    'bacabank' => 'Bac A Bank - Ngân hàng TMCP Bắc Á',
    'pvcombank' => 'PVcomBank - Ngân hàng TMCP Đại Chúng Việt Nam',
    'namabank' => 'Nam A Bank - Ngân hàng TMCP Nam Á',
    'saigonbank' => 'SaigonBank - Ngân hàng TMCP Sài Gòn Công Thương',
    'vietabank' => 'VietABank - Ngân hàng TMCP Việt Á',
    'baovietbank' => 'BaoViet Bank - Ngân hàng TMCP Bảo Việt',
    'kienlongbank' => 'KienlongBank - Ngân hàng TMCP Kiên Long',
    'abbank' => 'ABBank - Ngân hàng TMCP An Bình',
    'dongabank' => 'DongA Bank - Ngân hàng TMCP Đông Á',
    'vietbank' => 'VietBank - Ngân hàng TMCP Việt Nam Thương Tín',
    'pgbank' => 'PGBank - Ngân hàng TMCP Xăng dầu Petrolimex',
    'cbbank' => 'CB Bank - Ngân hàng TM TNHH MTV Xây dựng Việt Nam',
    'uob' => 'UOB - Ngân hàng TNHH MTV United Overseas Bank Việt Nam',
    'hsbc' => 'HSBC - Ngân hàng TNHH MTV HSBC (Việt Nam)',
    'standardchartered' => 'Standard Chartered - Ngân hàng TNHH MTV Standard Chartered (Việt Nam)',
    'shinhanbank' => 'Shinhan Bank - Ngân hàng TNHH MTV Shinhan Việt Nam',
    'wooribank' => 'Woori Bank - Ngân hàng TNHH MTV Woori Việt Nam',
];
